### ISSUE TITLE
DataLoader Performance improvement

### ISSUE THREAD

**Issue by gitttt-1234** [talmolab/sleap-nn#58]
The primary bottleneck in our training pipeline is the dataloader performance (currently training time per epoch is very high due to the dataloader - IterDatapipe). 

We should implement the PreLoader module (check [SLEAP](https://github.com/talmolab/sleap/blob/43a4f13ab28d2726af4a9c1858e8e2cde06d53cc/sleap/nn/data/dataset_ops.py#L276)) in Sleap-NN and benchmark the training time. The training time should be optimized to improve/ match the current SLEAP performance.

Ref (current Torch issue): https://github.com/pytorch/data/issues/1196

**Comment by talmo** [comment]
Profile!! --> https://lightning.ai/docs/pytorch/stable/tuning/profiler_basic.html

Break down the performance by steps, adding one block of the preloader at a time.

**Comment by gitttt-1234** [comment]
We compared and benchmarked the performance of IterDatapipes with LitData, and found that LitData is much faster and efficient API for data processing. #80 addresses the required refactoring for our current data pipeline
