### ISSUE TITLE
VideoReader Performance improvement

### ISSUE THREAD

**Issue by gitttt-1234** [talmolab/sleap-nn#59]
We need to improve the Inference pipeline with the VideoReader provider. First, we need to benchmark each step in the VideoReader to identify the bottleneck and then speed-up the inference on videos. 

- [ ] Check backend type
- [ ] Change backend and check the performance of video loader. Backends = `imageio_ffmpeg`, `pyav`
```
sio.load_video(..., plugin="opencv")
```

**Comment by talmo** [comment]
Closed after discussion.

Video decoding performance is an upstream concern of `sleap-io`.

On this end, we already have a multithreaded buffered video reader, which is the best we can possibly do.

The changes that need to happen to improve performance now just have to do with the data pipeline framework we use, and will be handled once we refactor data loading/preprocessing and inference model construction.
